const ACTION_PREFIX = '@@api-client';
export const API_REQUEST = `${ACTION_PREFIX}/API_REQUEST/`;
export const API_REQUEST_SUCCESS = `${ACTION_PREFIX}/API_REQUEST_SUCCESS/`;
export const API_REQUEST_FAILURE = `${ACTION_PREFIX}/API_REQUEST_FAILURE/`;
